#!/bin/sh

# The scratchpad will live on an unused tag:
scratch_tag=$((1 << 20 ))

# Toggle the scratchpad:
riverctl map normal Mod1 Minus toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad:
riverctl map normal Mod1+Shift Minus set-view-tags ${scratch_tag}

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set:
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}
