---
# The editor to use with 'cheat edit [note]'. Defaults to $EDITOR or $VISUAL.
editor: nvim

# Should 'cheat' always colorize output?
colorize: true

# Which 'chroma' colorscheme should be applied to the output?
# Options are available here:
#   https://github.com/alecthomas/chroma/tree/master/styles
style: monokai

# Which 'chroma' "formatter" should be applied?
# One of: "terminal", "terminal256", "terminal16m"
formatter: terminal256

# Through which pager should output be piped?
# 'less -FRX' is recommended on Unix systems
# 'more' is recommended on Windows
pager: less

# Notebooks are paths at which notes are available on your local filesystem.
#
# It is useful to sort notes into different notebooks for organizational
# purposes. For example, you might want one notebook for community
# notes, one for personal notes, one for notes pertaining to
# your day job, one for code snippets, etc.
#
# notebooks are scoped, such that more "local" notebooks take priority over
# more "global" notebooks. (The most global notebook is listed first in this
# file; the most local is listed last.) For example, if there is a 'tar'
# note on both global and local paths, you'll be presented with the local
# one by default. ('cheat -p' can be used to view notes from alternative
# notebooks.)
#
# notebooks can also be tagged as "read only". This instructs cheat not to
# automatically create notes on a read-only notebook. Instead, when you
# would like to edit a read-only note using 'cheat -e', cheat will
# perform a copy-on-write of that note from a read-only notebook to a
# writeable notebook.
#
# This is very useful when you would like to maintain, for example, a
# "pristine" repository of community notes on one notebook, and an
# editable personal reponsity of notes on another notebook.
#
# notebooks can be also configured to automatically apply tags to notes
# on certain paths, which can be useful for querying purposes.
# Example: 'cheat -t work jenkins'.
#
# Community notes must be installed separately, though you may have
# downloaded them automatically when installing 'cheat'. If not, you may
# download them here:
#
# https://github.com/cheat/notes
notebooks:
  # notebook properties mean the following:
  #   'name': the name of the notebook (view with 'cheat -d', filter with 'cheat -p')
  #   'path': the filesystem path of the note directory (view with 'cheat -d')
  #   'tags': tags that should be automatically applied to sheets on this path
  #   'readonly': shall user-created ('cheat -e') notes be saved here?
  - name: community
    path: /home/y/.config/cheat/notes/community
    tags: [ community ]
    readonly: true

  # If you have personalized notes, list them last. They will take
  # precedence over the more global notes.
  - name: personal
    path: /home/y/.config/cheat/notes/personal
    tags: [ personal ]
    readonly: false

  # While it requires no configuration here, it's also worth noting that
  # cheat will automatically append directories named '.cheat' within the
  # current working directory to the 'notebook'. This can be very useful if
  # you'd like to closely associate notes with, for example, a directory
  # containing source code.
  #
  # Such "directory-scoped" notes will be treated as the most "local"
  # notes, and will override less "local" notes. Similarly,
  # directory-scoped notes will always be editable ('readonly: false').
